### ISSUE TITLE
[feature request] Publish JSON file for released package set

### ISSUE THREAD

**Issue by chenyan-dfinity** [dfinity/vessel-package-set#22]
So that people can extract package info programmatically. One use case is for Motoko playground to import packages from the package set.

**Comment by kritzcreek** [comment]
Sorry I failed to respond yesterday.

What prohibits you from working with the dhall file instead? It's not hard to produce the json file, I'd just prefer people use the actual format.

**Comment by chenyan-dfinity** [comment]
We want to access the package info from JavaScript. The easiest is a JSON file, because http fetch response supports JSON. We would need a parser for dhall instead, which will increase the frontend size. The other problem is that the main dhall file refers to other dhall files in the repo, we would need at least an "evaluated" version of dhall to get the current package info.

**Comment by chenyan-dfinity** [comment]
I see. Adding the JSON would be great for JS.

Another question: the `version` field means either a tag or a commit hash?

**Comment by kritzcreek** [comment]
See https://github.com/dfinity/vessel-package-set/releases/tag/mo-0.6.1-20210610

Implemented in #23 and #24

> Another question: the version field means either a tag or a commit hash?

It means git-ref.. but ideally it would just be versions. The main reason it isn't, is because `base` still doesn't publish with semantic versioning and tags according to dfx releases instead.

**Comment by chenyan-dfinity** [comment]
Thanks! Now that we open sourced Motoko, the base can just use moc's version. We don't even need `next-moc` branch, because we can run CI from master.

**Comment by chenyan-dfinity** [comment]
Actually, I need `PackageInfo.dhall`, which contains the `description` field.

**Comment by chenyan-dfinity** [comment]
Seems I cannot fetch `https://github.com/dfinity/vessel-package-set/releases/download/mo-0.6.1-20210610/package-set.json` from frontend.
```
Access to fetch at 'https://github.com/dfinity/vessel-package-set/releases/download/mo-0.6.1-20210610/package-set.json' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Fetching from `dfinity.github.io` works. Is there a way to put the JSON file there?

**Comment by kritzcreek** [comment]
Can you just bake a package-set that matches the compiler your webpage ships into your build?

That way you can use dhall to include exactly the information you care about.
