### ISSUE TITLE
problem on WSl2 

### ISSUE THREAD

**Issue by dragon-raja** [dfinity/vessel-package-set#44]
when I use dfx build --check 
it happens

Building canisters to check they build ok. Canister IDs might be hard coded.
Building canisters...
The build step failed for canister 'cs7ap-qc5fi-rjs6g-k5hmq' with an embedded error: The command '"vessel" "sources"' failed with exit status 'exit status: 101'.
Stdout:

Stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/dfinity/vessel-package-set/releases/download/mo-0.6.18-20220107/package-set.dhall", query: None, fragment: None }, source: TimedOut }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/dhall-0.10.1/src/semantics/resolve/resolve.rs:295:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by rvanasa** [comment]
Closing since this should be fixed for the latest versions of `moc` (0.7.5) + `dfx` (0.12.1) + Vessel (0.6.5). Otherwise, please let me know and I will reopen this issue.
