### ISSUE TITLE
Plans to release a new vessel-package-set?

### ISSUE THREAD

**Issue by ByronBecker** [dfinity/vessel-package-set#50]
There have been some great additions/improvements/fixes to base and other libraries since the last release (Feb 2022).

It would be great if this package set (that many projects use by default) could be tagged and released in tandem with `moc 0.6.xx` updates, or at least on a more regular basis 🙂 .

@crusso @chenyan-dfinity

**Comment by crusso** [comment]
Err, I wish I knew how. @chenyan-dfinity, @rvanasa ever done this?

**Comment by crusso** [comment]
Ok, looks like I've managed to do this in the past. 
One question though, should we just do:

1. a new release for moc 0.6.29 for the latest dfx, 
2. releases for all the interim releases of moc/base
3.  release for all the interim release of moc/base included in some dfx.

**Comment by ByronBecker** [comment]
> 2\. releases for all the interim releases of moc/base

This would be preferred if possible, but if that's too frequent/cumbersome maybe try to do this.

> 3\. release for all the interim release of moc/base included in some dfx.

Also, for each release it might be nice to include the shasum of the new vessel-package-set in the `README.md` or some other `VERSIONS.md`. This allows developers to perform a semantic integrity check of their imports in the `package-set.dhall`

I was curious about how to do this, so I asked [here](https://forum.dfinity.org/t/do-people-actually-use-vessel/9849/5), and Christoph replied [here](https://forum.dfinity.org/t/do-people-actually-use-vessel/9849/8)

**Comment by crusso** [comment]
> > 2. releases for all the interim releases of moc/base
> 
> This would be preferred if possible, but if that's too frequent/cumbersome maybe try to do this.

Just to be clear, I was asking if we should do this for the past release since 0.6.21 (so 8 small PRs ;->) 

> > 3. release for all the interim release of moc/base included in some dfx.
(similar)
 
> Also, for each release it might be nice to include the shasum of the new vessel-package-set in the `README.md` or some other `VERSIONS.md`. This allows developers to perform a semantic integrity check of their imports in the `package-set.dhall`

> I was curious about how to do this, so I asked [here](https://forum.dfinity.org/t/do-people-actually-use-vessel/9849/5), and Christoph replied [here](https://forum.dfinity.org/t/do-people-actually-use-vessel/9849/8)

Yeah, I'm a little out of my depth here. Are you saying add a Makefile target to update a `Versions.md` to contain current dhall hash of package-set.dhall and then maybe get CI to check its up-to-date? How stable are those hashes for dhall versions?

Alternatively, I guess you could open a PR do to what you suggest, and I'll go through the manual steps of upgrading the package sets...

**Comment by ByronBecker** [comment]
> Just to be clear, I was asking if we should do this for the past release since 0.6.21 (so 8 small PRs ;->)

Oh no, I would just do it from here on going forwards.

As for the package set version to shasum hash, I would just set up something akin to what Quint has done with his package-set here https://github.com/aviate-labs/package-set

**Comment by ByronBecker** [comment]
@rvanasa @kentosugama 

Would love to have an update here for 0.6.29+. There are a bunch of library functions/bug fixes that are now missing (were added on later) which aren't coming through with this old of a package set.

**Comment by ByronBecker** [comment]
Ah, it looks like this PR just need an additional approval! https://github.com/dfinity/vessel-package-set/pull/52

**Comment by rvanasa** [comment]
Definitely! Apologies for somehow missing this conversation back in August. 

I'll look into updating the official package-set as soon as I receive write permissions for this repository.

**Comment by ByronBecker** [comment]
@crusso @rvanasa bump 😄 

I think either of you just need to push up a new tag with mo-<moc-version>-<year><month><day>.

At the same time, if this vessel package set isn't maintained, I'd recommend deprecating it and instead just have people use base directly referencing the release tag or commit hash like 

```
// package-set.dhall

let Package = { name : Text, version : Text, repo : Text, dependencies : List Text }

let packages = [
  { name = "base"
  , repo = "https://github.com/dfinity/motoko-base"
  , version = "moc-0.7.2"
  , dependencies = [ "base" ]
  }
]: List Package

in packages
```

**Comment by rvanasa** [comment]
We are working on this right now (squeezing in some base library PRs before the next dfx release). I'll make sure to ping this issue once we update the package-set.

**Comment by rvanasa** [comment]
Released! Let me know if you run into any hiccups with the new package-set.
